src/objects/Printer_Message__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Printer_Name__c</fullName>
        <label>Printer Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Printer Message</label>
    <nameField>
        <displayFormat>PM-{00000}</displayFormat>
        <label>Printer Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Printer Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PrinterResponseServiceTest.cls
@isTest
public class PrinterResponseServiceTest{
    static testmethod void testSimple() {
        Printer_Message__c testMessage = new Printer_Message__c();
        testMessage.Printer_Name__c = 'AAA';
        testMessage.Message__c = '/api/onetwothree';
        testMessage.Body__c = 'nothing';
        insert testMessage;
        
        String result = PrinterResponseService.handleResponse(testMessage.id, 'OK');
        Printer_Message__c updatedMessage = [Select Id, Response__c from Printer_Message__c Where Id = :testMessage.id];
        system.assertEquals('OK', updatedMessage.Response__c);
    }
}